server:
  port: 8888
spring:
  application:
    name: config-server
  profiles:
    active: native
  config:
    activate:
      on-profile:
  cloud:
      config:
        server:
          native:
            search-locations: C:/logs/ms-config-properties/{application}/{profile}/
          bootstrap: true
eureka:
  client:
    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      defaultZone: ${http://discovery:8761/eureka}
